import oandapysuite

ins = input("What instrument do you want to trade:")
gran = input("What timeframe do you want to trade:")
count = input("How many candles:")
api = oandapysuite.api.API()
c = api.get_candles(ins, gran, int(count))
sma = oandapysuite.SMA(on='close', period=120, color='purple', name='sma 100')
avdiff = oandapysuite.objects.indicators.AverageDifference(period=60, on='open', name='altav', color='black')
stdforprice = oandapysuite.objects.indicators.SampleStandardDeviation(on='close', period=120, color='orange', name='std 60')
zscore = oandapysuite.objects.indicators.ZScoreOfPrice(stdforprice, on='close', period=120, color='black', name='zscore')
signal = oandapysuite.objects.signals.AvDiffSignal()
sim = oandapysuite.objects.trade.Backtester(c, api, speed_factor=3000, ticks_per_second=700, generate_for='M1', indicators=[avdiff, sma, stdforprice, zscore], signal=signal)
sim.run()
print(sim.trades)